# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.12-alpine

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - apk add zip
  - apk add make

build:
  script:
    - cd daac
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - make html
    - cd build
    - zip -r html.zip html
  artifacts:
    paths:
      - daac/build/html.zip
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - changes:
        paths: 
        - daac//*

terraform-build:
  stage: test
  script:
    - cd iac-docker
    - terraform init
    - terraform validate
    - terraform plan
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - changes:
        paths: 
        - iac-docker//*
        - flask-docker//*