# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.12-alpine

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

build-daac:
  stage: test
  script:
    - python --version ; pip --version  # For debugging
    - apk add zip
    - apk add make
    - cd daac
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - make html
    - cd build
    - zip -r html.zip html
  artifacts:
    paths:
      - daac/build/html.zip
  rules: 
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        paths: 
        - daac/**/*

terraform-build:
  image: ubuntu:24.04
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  stage: test
  script:
    - apt-get update && apt-get install -y gnupg software-properties-common wget gpg coreutils gnupg software-properties-common
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update -y && apt install -y terraform
    - terraform --version
    - cd iac-docker
    - terraform init
    - terraform plan -out=${CI_PROJECT_DIR}/plan.json
    - terraform show --json ${CI_PROJECT_DIR}/plan.json
  rules: 
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        paths: 
        - iac-docker/**/*
        - flask-docker/**/*
  artifacts:
    reports:
      terraform: plan.json


terraform-apply:
  image: ubuntu:24.04
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  stage: deploy
  script:
    - apt-get update && apt-get install -y gnupg software-properties-common wget gpg coreutils gnupg software-properties-common
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update -y && apt install -y terraform
    - terraform --version
    - cd iac-docker
    - terraform init
    - terraform apply -auto-approve
  rules: 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        paths: 
        - iac-docker/**/*
        - flask-docker/**/*

terraform-build-101:
  image: ubuntu:24.04
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  stage: test
  script:
    - apt-get update && apt-get install -y gnupg software-properties-common wget gpg coreutils gnupg software-properties-common
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update -y && apt install -y terraform
    - terraform --version
    - cd iac-modelo-101
    - terraform init
    - terraform plan -out=${CI_PROJECT_DIR}/plan.json
    - terraform show --json ${CI_PROJECT_DIR}/plan.json
  rules: 
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        paths: 
        - iac-modelo-101/**/*
  artifacts:
    reports:
      terraform: plan.json

terraform-apply-101:
  image: ubuntu:24.04
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  stage: deploy
  script:
    - apt-get update && apt-get install -y gnupg software-properties-common wget gpg coreutils gnupg software-properties-common
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update -y && apt install -y terraform
    - terraform --version
    - cd iac-modelo-101
    - terraform init
    - terraform apply -auto-approve
  rules: 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        paths: 
        - iac-modelo-101/**/*

terraform-build-iris:
  image: ubuntu:24.04
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  stage: test
  script:
    - apt-get update && apt-get install -y gnupg software-properties-common wget gpg coreutils gnupg software-properties-common
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update -y && apt install -y terraform
    - terraform --version
    - cd iris/irismlops/iac/terraform
    - terraform init
    - terraform plan -out=${CI_PROJECT_DIR}/plan.json
    - terraform show --json ${CI_PROJECT_DIR}/plan.json
  rules: 
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        paths: 
        - iris/irismlops/iac/terraform/**/*
  artifacts:
    reports:
      terraform: plan.json

terraform-apply-iris:
  environment: $JOB_ENVIRONMENT
  image: ubuntu:24.04
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  stage: deploy
  script:
    - apt-get update && apt-get install -y gnupg software-properties-common wget gpg coreutils gnupg software-properties-common curl
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt update -y && apt install -y terraform docker-ce-cli
    - terraform --version
    - cd iris/irismlops/iac/terraform
    - terraform init
    - terraform workspace select $TERRAFORM_WORKSPACE
    - terraform apply -auto-approve
    - terraform output --json
  rules: 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        paths: 
        - iris/irismlops/iac/terraform/**/*
      variables:
        JOB_ENVIRONMENT: develop
        TERRAFORM_WORKSPACE: default
    - if: $CI_COMMIT_TAG =~ /^releases.*/
      changes: 
        paths: 
        - iris/irismlops/iac/terraform/**/*
      variables:
        JOB_ENVIRONMENT: production
        TERRAFORM_WORKSPACE: prod

deploy-function:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    - echo "Logging into Azure"
    - cd iris/irismlops/backend-fn
    - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
    - echo "Deploying to Azure App Service"
    - func azure functionapp publish "tomfunction" --python --force  # Publicamos la función en Azure
    - cd ../../
    - pwd



